version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/audit
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/authn
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/embargo
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/file_scan
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/intel
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/react-audit-log-viewer
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: npm
    directory: /examples/redact
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/vault
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/pangea-node-sdk
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/react-auth
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: npm
    directory: /packages/react-mui-audit-log-viewer
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"

  - package-ecosystem: npm
    directory: /packages/react-mui-authn
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"

  - package-ecosystem: npm
    directory: /packages/react-mui-branding
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"

  - package-ecosystem: npm
    directory: /packages/react-mui-shared
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"

  - package-ecosystem: npm
    directory: /packages/react-mui-store-file-viewer
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"

  - package-ecosystem: npm
    directory: /packages/vanilla-js
    versioning-strategy: increase
    schedule:
      interval: daily
