.example_audit_base:
  image: cypress/browsers:node18.12.0-chrome103-ff107
  before_script:
    - cd examples/audit
    - npm ci --legacy-peer-deps
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - examples/audit/**/*
      when: on_success

.validate_example_audit_is_latest:
  extends: .example_audit_base
  stage: Lint
  script:
    - cp ../../scripts/validate_latest_installed.sh .
    - ./validate_latest_installed.sh @pangeacyber/react-audit-log-viewer
    - ./validate_latest_installed.sh @pangeacyber/react-branding
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - packages/react-audit-log-viewer/**/*
        - packages/react-branding/**/*
      when: on_success

test_example_audit_app:
  extends: .example_audit_base
  stage: Integration Test
  script:
    - npm run cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
